services:
  - type: web
    name: ukfoodsaver-recommendations
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PYTHONPATH
        value: /opt/render/project/src